[platformio]
default_envs = esp32wroom
src_dir = esp32_beacon_firmware

[env:esp32wroom]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

# Suporte adicional caso esteja utilizando ESP32-CAM ou ESP32-S3/C3
[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
